name: JumpRace
version: 1.1.1
author: VoxCrafter_LP
main: com.voxcrafterlp.jumprace.JumpRace

commands:
  jumprace:
    description: Main command for the builderserver
  jr:
    description: Main command for the builderserver
  setup:
    description: Setup command for the maps
  start:
    description: Skip the lobby countdown