name: JumpRace
version: 1.0.0
author: VoxCrafter_LP
main: com.voxcrafterlp.jumprace.JumpRace

commands:
  jumprace:
    description: Main command for the builderserver
  jr:
    description: Main command for the builderserver
  setup:
    description: Setup command for the maps